
#set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_NAME nmpp-${PACK_BOARD})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Neuro Matrix Performance Primitives")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_VENDOR "RC Module")

#set(CPACK_SOURCE_IGNORE_FILES "build.*/;\\.git.*;\\.vscode;.*\\.o;.*lib.*\\.a;lib/")
set(CPACK_SOURCE_IGNORE_FILES "build.*/;\.git.*;\.vscode;.*\.o;.*lib.*\.a;lib/;hal/;nmpp/;.*\.abs;nmtp/;CMakeLists\.txt\.user")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})


set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)#ONE_PER_GROUP)
#set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)

include(CPack)
